---
- name: Install required apt packages
  when: ansible_distribution == 'Ubuntu'
  apt: update_cache=yes pkg={{ item }} state=installed
  with_items:
    - fail2ban
    - logwatch
    - unattended-upgrades
