---
- name: Remove 'sudo' group access
  lineinfile: dest=/etc/sudoers regexp="^%sudo" state=absent

- name: Add sudo access for Vagrant user
  when: vagrant is defined and vagrant
  lineinfile: dest=/etc/sudoers regexp="vagrant ALL"
              line="deploy ALL=(ALL) ALL" state=present

- name: Disable password authentication for ssh
  lineinfile: >
              dest=/etc/ssh/ssh_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no" state=present
  notify: Restart ssh
