---
- name: Configure periodic updates
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

- name: Restrict updates to security updates only
  lineinfile: >
              dest=/etc/apt/apt.conf.d/50unattended-upgrades
              regexp="{{  ubuntu_release }}-updates"
              state=absent
